
INSERT INTO public.app_updates (title, description, update_type, version, is_active, created_at) VALUES
('Icon-Only Toolbar', 'Replaced Add SIM Card, Expand/Collapse All, and Grid/List View buttons with clean icon-only controls with tooltip hints on hover. The interface is now more compact and streamlined.', 'improvement', '3.8.0', true, '2026-02-24 00:06:00+00'),
('Comprehensive Change History', 'All SIM card changes are now automatically tracked in the history timeline — including status changes (inactive, swapped), location changes, field edits (phone, SIM number, carrier, type, notes, login, password, account). Every modification creates an audit trail entry.', 'feature', '3.8.0', true, '2026-02-24 00:05:00+00'),
('History Button on Mobile', 'Added a blue History button to the collapsed mobile SIM card view alongside edit, swap, and delete buttons. History is now accessible without expanding the card. Timeline now displays oldest to newest.', 'improvement', '3.8.0', true, '2026-02-24 00:04:00+00'),
('Show/Hide Password Icon', 'Replaced the "Show password" checkbox with an Eye/EyeOff toggle icon across all views. The icon includes a tooltip on hover for clarity.', 'improvement', '3.8.0', true, '2026-02-24 00:03:00+00'),
('Universal Tooltips', 'Added 1-second hover tooltips to every icon in the application, including login, password, phone, SIM type, location, created, and last updated icons. A reusable TooltipIcon component powers all tooltips consistently.', 'feature', '3.8.0', true, '2026-02-24 00:02:00+00'),
('Mobile Navigation Overhaul', 'Redesigned the mobile header with a right-aligned hamburger menu, compact SIMCardSta.sh branding, and removed empty space between header and search bar. The Sideways Living logo is now hidden on mobile for a cleaner layout.', 'improvement', '3.8.0', true, '2026-02-24 00:01:00+00'),
('Swapped SIM Strikethrough', 'SIM cards with "swapped" status now consistently show strikethrough on both phone number and SIM number across all views (grid, list, and mobile).', 'bugfix', '3.8.0', true, '2026-02-24 00:00:00+00'),
('Updated Branding', 'Footer copyright updated to © 2026 SIMCardSta.sh. Mobile title changed to SIMCardSta.sh for consistent branding.', 'improvement', '3.8.0', true, '2026-02-23 23:59:00+00');
