// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zltcbjwkbzmuqiwqsfwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsdGNiandrYnptdXFpd3FzZnd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MzQzNDksImV4cCI6MjA2ODUxMDM0OX0.e053-SlzKxMp4SI6y7QZMD89Qz12n9wXeM_XwmAXSbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});